# Generated by Django 5.0.3 on 2024-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
