# Generated by Django 5.0.3 on 2024-04-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_answers_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default='abc', max_length=30),
        ),
    ]
