# Generated by Django 5.0.3 on 2024-04-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
    ]
