# Generated by Django 5.0.3 on 2024-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_remove_signup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='querry',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
