# Generated by Django 5.0.3 on 2024-04-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_querry_viewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.querry'),
        ),
    ]
