# Generated by Django 5.0.3 on 2024-04-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_answers_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
